export default function(){
    return[
        {
            id:1,
            first:'Jack',
            last:'Lwis',
            age:25
        },
        {
            id:2,
            first:'Jonath',
            last:'chan',
            age:65
        },
        {
            id:3,
            first:'David',
            last:'James',
            age:45
        }
    ]
}